# ======================== Filebeat Configuration =========================
name: filebeat

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

# =========================== Autodiscover ==============================
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: filestream
        id: default-container-${data.container.id}
        paths:
          - /var/lib/docker/containers/${data.container.id}/*-json.log
        parser:
          - container:
      templates:
        - condition:
            contains:
              docker.container.image: elasticsearch
          config:
            - module: elasticsearch
              server:
                input:
                  type: container
                  paths:
                    - /var/lib/docker/containers/${data.container.id}/*-json.log
        - condition:
            contains:
              docker.container.labels.service: backend # Hoặc một label/điều kiện khác phù hợp
          config:
            - type: filestream
              id: erpnext-backend-${data.container.id}
              paths:
                - /var/lib/docker/containers/${data.container.id}/*-json.log
              parsers:
                - container:
              fields:
                app: erpnext
                component: backend
              fields_under_root: true

              multiline.type: pattern
              multiline.pattern: '^\s'
              multiline.negate: false
              multiline.match: after
        - condition:
            contains:
              docker.container.labels.service: frontend
          config:
            - type: filestream
              id: erpnext-frontend-${data.container.id}
              paths:
                - /var/lib/docker/containers/${data.container.id}/*-json.log
              parsers:
                - container:
              fields:
                app: erpnext
                component: frontend
              fields_under_root: true
        - condition:
            contains:
              docker.container.labels.service: db # For MariaDB service
          config:
            - module: mysql
              error:
                enabled: true
                input:
                  type: container
                  paths:
                    - /var/lib/docker/containers/${data.container.id}/*-json.log
              slowlog:
                enabled: true
                input:
                  type: container
                  paths:
                    - /var/lib/docker/containers/${data.container.id}/*-json.log
              # You might need to add fields here if the module doesn't add enough context
              # fields:
              #   app: erpnext
              #   component: database
              # fields_under_root: true
        - condition:
            contains:
              docker.container.labels.service: redis-cache
          config:
            - module: redis
              log:
                enabled: true
                input:
                  type: container
                  paths:
                    - /var/lib/docker/containers/${data.container.id}/*-json.log
              # fields:
              #   app: erpnext
              #   component: redis-cache
              # fields_under_root: true
        - condition:
            contains:
              docker.container.labels.service: websocket
          config:
            - type: filestream
              id: erpnext-websocket-${data.container.id}
              paths:
                - /var/lib/docker/containers/${data.container.id}/*-json.log
              parsers:
                - container: {}
              fields:
                app: erpnext
                component: websocket
              fields_under_root: true
              multiline.type: pattern
              multiline.pattern: '^\s'
              multiline.negate: false
              multiline.match: after

# ============================ Processors ===============================
processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_host_metadata: ~

# ============================ Monitoring ===============================
monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}

# ============================ Output ===============================
output.logstash:
  hosts: ["logstash:5044"]
  loadbalance: false

http:
  enabled: true
  host: 0.0.0.0
