# ./logstash/config/pipelines.yml
- pipeline.id: main
  path.config: "/usr/share/logstash/pipeline/main.conf"

- pipeline.id: apps-pipeline
  path.config: "/usr/share/logstash/pipeline/apps.conf"

- pipeline.id: services-pipeline
  path.config: "/usr/share/logstash/pipeline/services.conf"

- pipeline.id: fallback-pipeline
  path.config: "/usr/share/logstash/pipeline/fallback.conf"

- pipeline.id: systems-pipeline
  path.config: "/usr/share/logstash/pipeline/systems.conf"
# - pipeline.id: metrics-pipeline
#   path.config: "/usr/share/logstash/pipeline/metrics_pipeline.conf"
