name: metricbeat

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
  - module: system
    period: 10s
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
    process.include_top_n:
      by_cpu: 5
      by_memory: 5
    enabled: true

  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ${ELASTICSEARCH_HOSTS}
  username: ${ELASTICSEARCH_USERNAME}
  password: ${BEATS_SYSTEM_PASSWORD}

- module: logstash
  xpack.enabled: true
  period: 10s
  hosts: ${LOGSTASH_HOST}  # Logstash must expose monitoring API

- module: kibana
  metricsets: [stats]
  period: 10s
  hosts: ${KIBANA_HOST}
  xpack.enabled: true
  username: ${ELASTICSEARCH_USERNAME}
  password: ${BEATS_SYSTEM_PASSWORD}

processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~
  - add_docker_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: ${ELASTICSEARCH_USERNAME}
    password: ${BEATS_SYSTEM_PASSWORD}
    hosts: [http://elasticsearch:9200]

output.kafka:
  hosts: ["kafka:29092"]
  topic: "metricbeat-logs-default"
  required_acks: 1
  compression: gzip

http:
  enabled: true
  host: 0.0.0.0
