name: metricbeat

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  enabled: true

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: [ "unix:///var/run/docker.sock" ]
  period: 10s
  enabled: true

processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~
  - add_docker_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}
    hosts: [ http://elasticsearch:9200 ]

output.logstash:
  hosts: ["logstash:5044"]

http:
  enabled: true
  host: 0.0.0.0